spring:
  application:
    name: pelicularestJpa
  datasource:
    url: jdbc:mysql://localhost:13306/mysql
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    
         
      
server:
  port: 8989
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8813/eureka/
      
      